config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_management.urls', namespace='task_management')),
    path('accounts/', include('allauth.urls')),
    path('ai_support/', include('ai_support.urls', namespace='ai_support')),
    path('lecture/', include('lecture.urls', namespace='lecture')),
    path('exam/', include('exam.urls', namespace='exam')),
]

exam/urls.py
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path("<int:topic_id>/mcq/main/", views.MultipleChoiceQuizView.as_view(), name="mcq_for_main_topic"),
    path("<int:topic_id>/mcq/sub/", views.MultipleChoiceQuizView.as_view(), name="mcq_for_sub_topic"),
]

task_management/urls.py
from django.urls import path

from . import views

app_name = 'task_management'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('set_native_language/', views.NativeLanguageSetView.as_view(), name='set_native_language'),
    path('interest-categories/', views.InterestCategoryListView.as_view(), name='interest_category_list'),
    path('interest-categories/add/', views.InterestCategoryCreateView.as_view(), name='interest_category_add'),
    path('interest-categories/<int:pk>/delete/', views.InterestCategoryDeleteView.as_view(), name='interest_category_delete'),
    path('learning-goals/<int:interest_id>', views.LearningGoalListView.as_view(), name='learning_goal_list'),
    path('learning-goals/<int:interest_id>/set/', views.LearningGoalSetView.as_view(), name='learning_goal_set'),
    path('learning-goals/draft/<int:draft_id>/preview/', views.LearningTopicPreviewView.as_view(), name='topic_preview'),
    path('learning-goals/draft/<int:draft_id>/finalize/', views.LearningGoalFinalizeView.as_view(), name='learning_goal_finalize'),
    path('learning-goals/<int:goal_id>/detail/', views.LearningGoalDetailView.as_view(), name='learning_goal_detail'),
    path('learning-goals/<int:goal_id>/delete/', views.LearningGoalDeleteView.as_view(), name='learning_goal_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <title>{% block title %}{% endblock title %}</title>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />

        {% block head %}{% endblock head %}
    </head>

    <body id="page-top" class="{% block body_class %}{% endblock body_class %}" >
        <div id='wrapper'>
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
                <div class="container px-4 px-lg-5">
                    <a class="navbar-brand" href="{% url 'task_management:index' %}">My-Studyapp</a>
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto my-2 my-lg-0">
                            <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                            {% if user.is_authenticated %}
                                <li class='nav-item'><a class="nav-link {% block active_logout %}{% endblock active_logout %}" href="{% url 'account_logout' %}">Log Out</a></li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link {% block active_login %}{% endblock active_login %}" href="{% url 'account_login' %}">Log In</a></li>
                                <li class="nav-item"><a class="nav-link {% block active_signup %}{% endblock active_signup %}" href="{% url 'account_signup' %}">Sign Up</a></li>
                            {% endif %}
                            <li class="nav-item"><a class="nav-link" href="#contact">Inquiry</a></li>
                        </ul>
                    </div>
                </div>
            </nav>

            {% block header %}{% endblock header %}
            {% block content %}{% endblock content %}

            <!-- Footer-->
            <footer class="bg-light py-5">
                <div class="container px-4 px-lg-5"><div class="small text-center text-muted">My-Studyapp &copy; 2025 - akinkat</div></div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- SimpleLightbox plugin JS-->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
            <!-- Core theme JS-->
            <script src="{% static 'js/scripts.js' %}"></script>
            <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
            <!-- * *                               SB Forms JS                               * *-->
            <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
            <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
            <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        </div>
    </body>
</html>